services:

  postgres:
    image: ankane/pgvector:latest
    container_name: cardwiz-postgres
    restart: always
    environment:
      POSTGRES_DB: cardwiz
      POSTGRES_USER: cardwiz_user
      POSTGRES_PASSWORD: cardwiz_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cardwiz-network

  redis:
    image: redis:7
    container_name: cardwiz-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cardwiz-network

  # Optional but VERY useful during development
  pgadmin:
    image: dpage/pgadmin4
    container_name: cardwiz-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cardwiz.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - cardwiz-network

  minio:
      image: minio/minio:latest
      container_name: cardwiz-minio
      restart: always
      command: server /data --console-address ":9001"
      environment:
        MINIO_ROOT_USER: minioadmin
        MINIO_ROOT_PASSWORD: minioadmin123
      ports:
        - "9000:9000"   # S3 API
        - "9001:9001"   # Web Console
      volumes:
        - minio-data:/data
      networks:
        - cardwiz-network


volumes:
  postgres_data:
  redis_data:
  minio-data:

networks:
  cardwiz-network:
    driver: bridge
