services:

  postgres:
    image: ankane/pgvector:latest
    container_name: cardwiz-postgres
    restart: always
    environment:
      POSTGRES_DB: cardwiz
      POSTGRES_USER: cardwiz_user
      POSTGRES_PASSWORD: cardwiz_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cardwiz-network

  redis:
    image: redis:7
    container_name: cardwiz-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cardwiz-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: cardwiz-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cardwiz.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - cardwiz-network

  minio:
    image: minio/minio:latest
    container_name: cardwiz-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - cardwiz-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: cardwiz-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - cardwiz-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: cardwiz-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Internal Docker communication
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - cardwiz-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  cardwiz-network:
    driver: bridge
